### PR TITLE
clean up bower.json. Remove '#', remove resolutions, remove urls. Ran…

### PR DESCRIPTION
**Pull request by mdwragg**
clean up bower.json. Remove '#', remove resolutions, remove urls. Ran `ncu` over it to pick up latest components deps. Moved '-design' repos to dev dependencies.

### CODE REVIEW

**Comment by mdwragg** [comment]
@davidrleonard can you review and merge this in please? If all acceptable can you tag and push a new version? @randyaskin is waiting on this as his builds are failing downstream.

Thanks!

**Comment by katemenkhaus** [comment]
Thanks Martin!

**Comment by davidrleonard** [comment]
Thanks for the PR, @mdwragg, and thanks for merging @Menkhaus-ge.

**Comment by mdwragg** [comment]
💯

**Pull request merged**
